# Generated by Django 3.2.25 on 2025-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishs', '0002_alter_dish_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
