# Generated by Django 3.2.25 on 2025-02-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
