# Generated by Django 3.2.25 on 2025-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishs', '0003_dish_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
